### PR TITLE
Update SNAP medical deductions

### LINKED ISSUE #2904: Update SNAP medical deductions
Thanks @benmolin for the report

Sources: https://frac.org/wp-content/uploads/SNAP-SMD-National-Report-1.pdf
+ [OR](https://oregon.public.law/rules/oar_461-160-0430) + [LA](https://www.kalb.com/2023/03/01/snap-extra-benefits-end-recipients-asked-update-info-assess-options/)

State
 Deduction 
AL	 $          175
AR	 $          138
CA	 $          120
CO	 $          165
GA	 $          136
IA	 $          125
ID	 $          144
IL	 $          185
KS	 $          175
LA	 $          161
MA	 $          155
MO	 $          135
ND	 $          200
NH	 $          115
OR	 $          170
RI	 $          183
SC	 $          175
SD	 $          180
TX	 $          135
VA	 $          200
VT	 $          156
WY	 $          138

https://github.com/PolicyEngine/policyengine-us/blob/6bdf9bb89ac989473eb80795ed2557b6f1206885/policyengine_us/parameters/gov/usda/snap/income/deductions/excess_medical_expense/standard.yaml

### PR DESCRIPTION
**Pull request by vrathi101**
Fixes #2904

### CODE REVIEW

**Review by MaxGhenis — COMMENTED** [review]
Do these values align with snapscreener?

I think they typically update in October

**Comment by vrathi101** [comment]
> Do these values align with snapscreener?
> 
> I think they typically update in October

everything but Michigan aligns, 
FRAC doesn't mention Michigan but the SNAP screener has a deduction of 165
I wasn't able to find any Michigan specific sources verifying/refuting this

**Comment by MaxGhenis** [comment]
@benmolin could you please point us to the source for SNAP Screener's medical deduction values?

**Comment by benmolin** [comment]
https://dhhs.michigan.gov/olmweb/ex/BP/Public/BEM/554.pdf#page=9

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
