### PR TITLE
Simplify calculation of dividend income from qualified and non-qualified dividends

### LINKED ISSUE #1221: Incorrect handling of non_qualified_dividend_income
Here is a YAML test case (which has some `non_qualified_dividend_income` but no `qualified_dividend_income`), the test results for which are shown below the case.
```
# OpenFisca-US test file derived from g21.its.csv and g21.ota.csv files
- name: Tax unit with taxsimid 4608 from g21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 24
        employment_income: 160000
        taxable_interest_income: 10000
        non_qualified_dividend_income: 15000
        social_security: 18000
        rent: 15000
        interest_expense: 25000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
      person4:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 16
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3, person4]
        state_code: TX
  output:
    taxsim_tfica: 11173.60
    income_tax: 29534.40
```

Here are the test results for the above case:
```
=============================== FAILURES ===================================
_____________________________ test session _________________________________
/Users/mrh/work/OpenFisca-US/US/g21-id4608.test.yaml:
  Test 'Tax unit with taxsimid 4608 from g21.its.csv':
    income_tax@2021: [30843.398] differs from 29534.400390625
      with an absolute margin [1308.998] > 0.01
======================= short test summary info ============================
FAILED g21-id4608.test.yaml::
============================ 1 failed in 1.04s ===============================
Trace output is in file: g21-id4608.test.trace
```

OpenFisca-US produces an income tax of about $30,843.40 while TAXSIM35 (and US Tax Analyzer) produce an income tax of about $29,534.40.  So, OpenFisca-US gets a tax that is about $1309 more than what the other two models get.

Among other things, the OpenFisca-US trace output contains this:
```
% grep qualified_dividend_income g21-id4608.test.trace | head -1
         qualified_dividend_income<2021> >> [6720.    0.    0.    0.]
% grep non_qualified_dividend_income g21-id4608.test.trace
%
```
The above trace output presents two puzzles:

(1) How does the $15,000 of `non_qualified_dividend_income` translate into $6720 of `qualified_dividend_income`?

(2) Why is there no `qualified_dividend_income` in the trace output?

It doesn't seem like OpenFisca-US is working as intended.   Or am I missing something?

### PR DESCRIPTION
**Pull request by martinholmer**
Fixes #1221.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thanks @martinholmer! This will also require moving the dividend-splitting logic to the CPS ingestion step. Do you want to take a look at that or do you need more specific pointers?

**Comment by martinholmer** [comment]
@MaxGhenis said:
> This will also require moving the dividend-splitting logic to the CPS ingestion step. Do you want to take a look at that or do you need more specific pointers?

Let's leave that to a different pull request that reassesses the CPS-to-PolicyEngineUS variable mappings.   I'll raise an issue on this topic later today.

**Comment by MaxGhenis** [comment]
Reassessing sounds good, though I think the microsimulation will fail to model dividends correctly if we merge this without also updating the CPS routine.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Reassessing sounds good, though I think the microsimulation will fail to model dividends correctly if we merge this without also updating the CPS routine.

OK, I'll add something to this pull request if you give me some guidance.

What is the answer to this question?
`How should dividends be split between qualified and non-qualified?`

**Comment by MaxGhenis** [comment]
We can use the qualified_percentage calibration parameter currently in the qualified_dividends formula

**Comment by martinholmer** [comment]
What does this error mean?
```
requests.exceptions.HTTPError: 503 Server Error: Egress is over the account limit.
```
This error is encountered with running the data tests as seen in this screenshot:
Screen Shot 2022-11-17 at 10 31 26 AM

Is there some kind of (monthly?) limit on the number of CPS dataset downloads?
Or have I done something wrong in pull request #1502?

**Review by MaxGhenis — APPROVED** [review]
Similar to #1507, I'm approving this, though we'll return to it in https://github.com/PolicyEngine/policyengine-us/issues/1513. We'll likely revive the `qualified_percentage.yaml` file at that point.

**Pull request merged**
