### PR TITLE
Uprate USDA and SGA parameters

### LINKED ISSUE #4060: Uprate SGA (SSA parameter)

### LINKED ISSUE #4061: Propagate SNAP and school meal uprating
For example, the SNAP max allotment has uprating metadata, but it's in a parent of the main/additional elements, and as a result isn't applying correctly: https://policyengine.org/us/policy?reform=2&focus=gov.usda.snap.max_allotment.additional.AK_RURAL_1&region=us&timePeriod=2024&baseline=2

WIC parameters have `propagate_metadata_to_children` and as a result work correctly: https://policyengine.org/us/policy?reform=2&focus=gov.usda.wic.value.CHILD&region=us&timePeriod=2024&baseline=2

### PR DESCRIPTION
**Pull request by MaxGhenis**
Fixes #4061
Fixes #4060

### CODE REVIEW

**Comment by MaxGhenis** [comment]
@nikhilwoodruff should we add empty values for these geographies, or can we push a core fix to treat empties as zeros?

**Comment by nikhilwoodruff** [comment]
Do you know where the `AP` is coming from in the error? Struggling to locate it

**Comment by MaxGhenis** [comment]
`AP` is a value of `snap_utility_region`, which is the breakdown for the limited utility allowance file. We don't have a value for it, which is causing the error.

**Comment by MaxGhenis** [comment]
Superseded by #4030

**Pull request closed without merging**
