### PR TITLE
Montana 2023 income tax rebate

### LINKED ISSUE #5338: Montana 2023 income tax rebate
[Reference](https://mtrevenue.gov/wp-content/uploads/dlm_uploads/2023/12/Form_2_2023_Instructions.pdf#page=5)

### PR DESCRIPTION
**Pull request by PavelMakarchuk**
Fixes #5338

### CODE REVIEW

**Review by MaxGhenis — COMMENTED** [review]
Don't we currently base other Covid rebates on the income in the year the income was considered? So 2021 in this case in 2023.

**Comment by PavelMakarchuk** [comment]
> Don't we currently base other Covid rebates on the income in the year the income was considered? So 2021 in this case in 2023.

We apply the rebate in the year that it is payed out e.g. the [Delaware rebate](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/de/tax/income/credits/relief_rebate/de_relief_rebate.py)

**Comment by MaxGhenis** [comment]
What about federal covid checks?

**Comment by PavelMakarchuk** [comment]
> What about federal covid checks?

We have not included covid checks into our rules engine yet

**Comment by MaxGhenis** [comment]
Yes we have, recovery rebate credits

**Comment by PavelMakarchuk** [comment]
> Yes we have, recovery rebate credits

I see, we provide those in 2020 (CAA & CARES) and ARPA in 2021 while the rebate amount is based on 2019 tax returns

**Comment by MaxGhenis** [comment]
OK I'll merge this but filed https://github.com/PolicyEngine/policyengine-us/issues/5368 to align to the income year.

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
