### PR TITLE
Cost of attending college variable adjustment

### LINKED ISSUE #2959: Cost of attending college variable adjustment
currently pell grant specific

### PR DESCRIPTION
**Pull request by PavelMakarchuk**
Fixes #2959

### Summary
📝🚚🏫

This pull request fixes the `cost_of_attending_college` variable adjustment and moves it to a more appropriate subpackage. It also adds a changelog entry for the patch-level update.

> _`cost_of_college`_
> _moved and renamed for clarity_
> _autumn of refactor_

### Walkthrough
* Move and rename the `cost_of_attending_college` variable class to the `household/expense/education` subpackage, and update its label ([link](https://github.com/PolicyEngine/policyengine-us/pull/2960/files?diff=unified&w=0#diff-59780eac55d9945c97edca209e4637dc266e7c41a518ca6b5126b48b1820c82bL7-R7))
* Add a changelog entry for the patch-level update that fixes the variable adjustment ([link](https://github.com/PolicyEngine/policyengine-us/pull/2960/files?diff=unified&w=0#diff-5885042762833a4aef51405a4036067e4e6aefa7a5091a2987d1d9d1fc2647e8R1-R4))

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Could you remind me the context of this? I expect that different programs will have different definitions that could include different sets of {tuition,room,board,fees,books}, so we might want to make more precise leaf-node variables and sum from there.

@CalebPena could you share how the Pell Grant program computes it?

**Comment by CalebPena** [comment]
@MaxGhenis Pell Grant subtracts the expected family contribution from the cost of attending college (capped at a maximum, and adjusted for part time students) to determine the Pell Grant Award.

**Comment by MaxGhenis** [comment]
What does the Pell Grant count as cost of the elements I listed above?

**Comment by CalebPena** [comment]
Cost of attendance is determined by each individual college, but it includes things like tuition, room and board, and books.

**Pull request closed without merging**
