### PR TITLE
Add SSDI Into MO Pension/SS/SSD Part C Formula

### PR DESCRIPTION
**Pull request by nmrodelo**
edit mo_pension_and_ss_or_ssd_deduction_section_c to include ssdi in amount used to calculate deduction.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Could you run `pip install black -U` and then `make format`? That should undo some of the extraneous formatting changes.

**Comment by MaxGhenis** [comment]
@martinholmer have you looked at this part of the MO tax?

IIRC the form only mentioned SSDI for clarity; the law itself referred to all Social Security payments.

**Comment by martinholmer** [comment]
In pull request #1766 @MaxGhenis asked me:
> [MH] have you looked at this part of the MO tax?

Yes, I have.   And I'm puzzled by this pull request.
This pull request is based on a branch called `issue1763`, but it seems to have nothing to do with the bug identified in issue #1763.

What this pull request does attempt to do is incorrect.  The form makes it clear that only **taxable** DI benefits can be deducted from MO AGI.  Another problematic thing about this pull request is the proliferation of variables that are components of social security (that is, OASDI) benefits.  If you merge this pull request, we will be in a situation analogous to the proliferation of unconnected pension variables that had to be dealt with recently.

My view is that this pull request should not be merged because it only (incorrectly) adds unnecessary complexity and does not fix the bug identified in issue #1763.

**Comment by nmrodelo** [comment]
@martinholmer @MaxGhenis  yep, see what you mean, misinterpreted the original issue. will tag both of you in the new pr meant to address #1763, closing this PR

**Pull request closed without merging**
