### PR TITLE
Hawaii standard deduction

### PR DESCRIPTION
**Pull request by HaolinXX**

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Could you please run `git pull upstream master`? This PR currently changes many files unrelated to the Hawaii standard deduction.

**Comment by HaolinXX** [comment]
> Could you please run `git pull upstream master`? This PR currently changes many files unrelated to the Hawaii standard deduction.

We already run git pull upstream master and everything is up to date.

**Comment by MaxGhenis** [comment]
Could you try `pip install -U black` and `make format`? These changes look formatting-related.

**Comment by HaolinXX** [comment]
> make format

**Comment by HaolinXX** [comment]
> Could you try `pip install -U black` and `make format`? These changes look formatting-related.

**Pull request closed without merging**
