### PR TITLE
Use modern (instead of out-dated) policyengine-core

### PR DESCRIPTION
**Pull request by martinholmer**
The current `setup.py` file restricts PolicyEngine-US to using an old version of `policyengine-core`.

Removing that restriction allows access to new core features and the "make test" command executes without test failures after fixing the `snap_region` formula in commit https://github.com/PolicyEngine/policyengine-us/pull/4840/commits/94fc9763187481790f6dcf944081113c49a51c12 and after some [repeal_head_of_household test revisions](https://github.com/PolicyEngine/policyengine-us/pull/4840/files#diff-45c53cc34b29531a68fc42a5a1e853f9a8994ef1d09315d4cc01a4ca2d11ab6c).

### CODE REVIEW

**Comment by MaxGhenis** [comment]
We pinned it because we were getting other test failures: https://github.com/PolicyEngine/policyengine-us/actions/runs/9331372467/job/25685961021#step:5:1675

**Comment by martinholmer** [comment]
Here is the error information from running locally the test @MaxGhenis mentioned earlier:
```
policyengine_us% pytest tests/microsimulation/reforms/test_repeal_head_of_household.py
============================= test session starts ==============================
platform darwin -- Python 3.9.13, pytest-8.2.1, pluggy-1.5.0
rootdir: /Users/mrh/work/policyengine-us
plugins: anyio-3.5.0, dependency-0.5.1
collected 1 item                                                               

tests/microsimulation/reforms/test_repeal_head_of_household.py F         [100%]

================================ FAILURES ================================
_____________________ test_repeal_head_of_household ______________________

    def test_repeal_head_of_household():
        from policyengine_us import Microsimulation
        from policyengine_core.reforms import Reform
        from policyengine_core.periods import instant
        from numpy.testing import assert_allclose
    
        class neutralize_reform(Reform):
            def apply(self):
                self.neutralize_variable("head_of_household_eligible")
    
        baseline = Microsimulation()
        neutralize_reformed = Microsimulation(reform=neutralize_reform)
    
>       baseline_net_income = baseline.calculate("household_net_income")

tests/microsimulation/reforms/test_repeal_head_of_household.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

...[SNIP]...
../../../opt/anaconda3/lib/python3.9/site-packages/policyengine_core/simulations/simulation.py:648: in _calculate
    array = self._run_formula(variable, population, period)
../../../opt/anaconda3/lib/python3.9/site-packages/policyengine_core/simulations/simulation.py:931: in _run_formula
    array = formula(population, period)
variables/gov/usda/snap/snap_region.py:39: in formula
    return SNAPRegion.encode(mapped_values)
../../../opt/anaconda3/lib/python3.9/site-packages/policyengine_core/enums/enum.py:57: in encode
    array = np.array([item.name for item in array])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <iterator object at 0x7ff298f751f0>

>   array = np.array([item.name for item in array])
E   AttributeError: 'float' object has no attribute 'name'

../site-packages/policyengine_core/enums/enum.py:57: AttributeError

===================== short test summary info ============================
FAILED
tests/microsimulation/reforms/test_repeal_head_of_household.py::
      test_repeal_head_of_household - AttributeError:
      'float' object has no attribute 'name'
======================== 1 failed in 29.84s ==============================
```

I don't see why this error is viewed as a problem with the newest version  of `policyengine-core`.

Doesn't the error message suggest that the SNAPRegion.encode(mapped_values) statement is being passed illegal `mapped_values`?

https://github.com/PolicyEngine/policyengine-us/blob/22a2c3c0d7715f81259c1b51e914ff6e963b7387/policyengine_us/variables/gov/usda/snap/snap_region.py#L15-L39

.

**The fact that this `snap_region` formula fails only under a reform that eliminates a filing status (namely HoH) seems like a more promising clue about what the nature of the real problem is.**

**Comment by martinholmer** [comment]
@martinholmer said in PR #4840:
> The key question is why is the `snap_region` formula generating illegal mapped_values.

The bug in the `snap_region` formula has been fixed in this PR's commit https://github.com/PolicyEngine/policyengine-us/pull/4840/commits/94fc9763187481790f6dcf944081113c49a51c12

**Comment by martinholmer** [comment]
Here is more information about the NaN values being generated in the repeal_head_of_household test by the neutralize reform:

```
E       AssertionError: assert False
E        +  where False = <function allclose at 0x7fbfa52fa1b0>(               value       weight\n0       32459.000000  1580.069946\n1       44800.367188  1789.599976\n2       19105.00...59504.453125   445.779999\n56837   79160.875000   413.200012\n56838   93797.250000   416.369995\n\n[56839 rows x 2 columns],                value       weight\n0       32459.000000  1580.069946\n1       44800.367188  1789.599976\n2       19105.00...59504.453125   445.779999\n56837   79160.875000   413.200012\n56838   93797.250000   416.369995\n\n[56839 rows x 2 columns])
E        +    where <function allclose at 0x7fbfa52fa1b0> = <module 'numpy' from '/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/numpy/__init__.py'>.allclose

test_repeal_head_of_household.py:64: AssertionError
----------------------------- Captured stdout call -----------------------------
baseline   NaN count 0
neutralize NaN count 60
parameter  NaN count 0
idx,bni,nni,pni= 15434 82214.61 nan 82214.61
idx,bni,nni,pni= 15441 40252.016 nan 40252.016
idx,bni,nni,pni= 15462 38085.344 nan 38085.344
idx,bni,nni,pni= 15481 51032.99 nan 51032.99
idx,bni,nni,pni= 15487 42229.266 nan 42229.266
idx,bni,nni,pni= 15498 49686.566 nan 49686.566
idx,bni,nni,pni= 15507 67465.67 nan 67465.67
idx,bni,nni,pni= 15517 71926.59 nan 71926.59
idx,bni,nni,pni= 15524 83933.0 nan 83933.0
idx,bni,nni,pni= 15528 114833.01 nan 114833.01
idx,bni,nni,pni= 15542 39934.1 nan 39934.1
idx,bni,nni,pni= 15545 44199.78 nan 44199.78
idx,bni,nni,pni= 15559 43298.99 nan 43298.99
idx,bni,nni,pni= 15567 40704.305 nan 40704.305
idx,bni,nni,pni= 15584 61940.19 nan 61940.19
idx,bni,nni,pni= 15612 43841.133 nan 43841.133
idx,bni,nni,pni= 15618 75232.39 nan 75232.39
idx,bni,nni,pni= 15632 40172.0 nan 40172.0
idx,bni,nni,pni= 15651 47249.668 nan 47249.668
idx,bni,nni,pni= 15665 126776.89 nan 126776.89
idx,bni,nni,pni= 15692 68620.06 nan 68620.06
idx,bni,nni,pni= 15698 21109.715 nan 21109.715
idx,bni,nni,pni= 15703 53660.1 nan 53660.1
idx,bni,nni,pni= 15707 110497.266 nan 110497.266
idx,bni,nni,pni= 15709 85444.445 nan 85444.445
idx,bni,nni,pni= 15726 123780.43 nan 123780.43
idx,bni,nni,pni= 15742 38813.3 nan 38813.3
idx,bni,nni,pni= 15743 24107.4 nan 24107.4
idx,bni,nni,pni= 15744 34793.7 nan 34793.7
idx,bni,nni,pni= 15767 78700.4 nan 78700.4
idx,bni,nni,pni= 15771 63339.613 nan 63339.613
idx,bni,nni,pni= 15775 41498.633 nan 41498.633
idx,bni,nni,pni= 15777 43939.58 nan 43939.58
idx,bni,nni,pni= 15782 83771.734 nan 83771.734
idx,bni,nni,pni= 15783 173543.22 nan 173543.22
idx,bni,nni,pni= 15796 50035.223 nan 50035.223
idx,bni,nni,pni= 15804 35880.227 nan 35880.227
idx,bni,nni,pni= 15821 52254.492 nan 52254.492
idx,bni,nni,pni= 15826 23031.465 nan 23031.465
idx,bni,nni,pni= 15827 73152.98 nan 73152.98
idx,bni,nni,pni= 15836 19662.4 nan 19662.4
idx,bni,nni,pni= 15844 84176.54 nan 84176.54
idx,bni,nni,pni= 15851 43681.414 nan 43681.414
idx,bni,nni,pni= 15869 37043.684 nan 37043.684
idx,bni,nni,pni= 15910 612319.6 nan 612319.6
idx,bni,nni,pni= 15916 94991.1 nan 94991.1
idx,bni,nni,pni= 15920 57683.164 nan 57683.164
idx,bni,nni,pni= 15922 35441.5 nan 35441.5
idx,bni,nni,pni= 15937 27123.4 nan 27123.4
idx,bni,nni,pni= 15941 66127.8 nan 66127.8
idx,bni,nni,pni= 15956 43445.688 nan 43445.688
idx,bni,nni,pni= 15961 31254.383 nan 31254.383
idx,bni,nni,pni= 15973 166179.86 nan 166179.86
idx,bni,nni,pni= 16013 103952.22 nan 103952.22
idx,bni,nni,pni= 16029 82216.164 nan 82216.164
idx,bni,nni,pni= 16037 43392.836 nan 43392.836
idx,bni,nni,pni= 16049 66407.22 nan 66407.22
idx,bni,nni,pni= 16058 97061.45 nan 97061.45
idx,bni,nni,pni= 16064 215284.52 nan 215284.52
idx,bni,nni,pni= 16066 91486.14 nan 91486.14
b_vs_p_diff_count= 0
=========================== short test summary info ============================
FAILED test_repeal_head_of_household.py::test_repeal_head_of_household - AssertionError: assert False
```

Notice that the baseline household net income and the parameter reform net income arrays contain no NaN values, while the neutralize reform net income array contains sixty NaN values.   And in every one of those sixty cases, the baseline and parameter-reform net income values are exactly the same.

@MaxGhenis, these results suggest a problem with the neutralize reform: why would there be NaN values for household net income under that reform?  It seems to me that there should never be any NaN values for household net income under **any** reform.   Or am I missing something?

Seems like there are NaN problems popping up in several places given issue #4835.

Given the information generated so far in PR #4840 (including the fact that fixing the snap_region formula made two of the three test failures go away), why do you think the modern version of policyengine-core is the problem?   If it is the problem, then shouldn't policyengine-core be fixed rather than restricting policyengine-us to use an out-of-date version of policyengine-core?

**Review by MaxGhenis — APPROVED** [review]
Thank you Martin! Would you suggest leaving these print statements for future debugging, or is the need now met? Will defer to your judgment.

**Comment by martinholmer** [comment]
@MaxGhenis said in PR #4840:
> Thank you Martin!  Would you suggest leaving these print statements for future debugging, or is the need now met? Will defer to your judgment.

I would leave them in because they will help developers who want to debug the parameter and neutralize reforms, both of which are used in the repeal_head_of_household test and both of which have problems.

**Pull request merged**
