### PR TITLE
Fix New Mexico Low Income Comprehensive Tax Rebate calculations

### LINKED ISSUE #4319: Fix New Mexico Low Income Comprehensive Tax Rebate calculations
The merge of pull request #4300 caused a regression in the NM integration testing results.

The following test illustrates the problem:
```
- name: Tax unit with taxsimid 98790 in p21.its.csv and p21.ots.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        age: 67
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person2:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person3:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
      person4:
        age: 11
        ssi: 0  # not in TAXSIM35
        state_supplement: 0  # not in TAXSIM35
        wic: 0  # not in TAXSIM35
        ma_covid_19_essential_employee_premium_pay_program: 0  # not in TAXSIM35
    tax_units:
      tax_unit:
        members: [person1, person2, person3, person4]
        premium_tax_credit: 0  # not in TAXSIM35
        local_income_tax: 0  # not in TAXSIM35
        state_sales_tax: 0  # not in TAXSIM35
        ca_use_tax: 0  # not in TAXSIM35
        il_use_tax: 0  # not in TAXSIM35
        nm_2021_income_rebate: 0  # not in TAXSIM35
        nm_additional_2021_income_rebate: 0  # not in TAXSIM35
        nm_supplemental_2021_income_rebate: 0  # not in TAXSIM35
        ny_supplemental_eitc: 0  # not in TAXSIM35
        ok_use_tax: 0  # not in TAXSIM35
        pa_use_tax: 0  # not in TAXSIM35
        vt_renter_credit: 0  # not in TAXSIM35
    spm_units:
      spm_unit:
        members: [person1, person2, person3, person4]
        snap: 0  # not in TAXSIM35
        tanf: 0  # not in TAXSIM35
    households:
      household:
        members: [person1, person2, person3, person4]
        state_fips: 35  # NM
  output:  # expected results from patched TAXSIM35 2024-03-26 version
    nm_income_tax: -520.00
```

### PR DESCRIPTION
**Pull request by xianxinzhu**
Fixes #4319

### CODE REVIEW

**Review by PavelMakarchuk — APPROVED** [review]

**Comment by PavelMakarchuk** [comment]
@MaxGhenis adjusting this code as it was failing integration tests with the default function

**Comment by MaxGhenis** [comment]
Can you describe the issue this is addressing? I don't see why we'd have to deviate from the law by adding a dollar to the thresholds.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Can you describe the issue this is addressing? I don't see why we'd have to deviate from the law by adding a dollar to the thresholds.

Agreed.   You are just undoing what was done in PR #4300 rather than figuring out the source of the problem in issue #4319.

**Comment by PavelMakarchuk** [comment]
I see what happened, the `right=True` function also applies to the first threshold value which in this case is 0. In rhis case, if AGI is 0, it seems to fall outside the range of the brackets and is returned as 0. 
To overcome this we can set the first threshold value to "-1" for all yaml files

**Comment by MaxGhenis** [comment]
if it's single_amount the left endpoint should be -.inf

**Comment by martinholmer** [comment]
@MaxGhenis said in PR #4346:
> if it's single_amount the left endpoint should be -.inf

I agree.   I don't see why a filer with NM AGI of -$100 would be ineligible for the rebate.

**Comment by PavelMakarchuk** [comment]
@MaxGhenis makes sense, adjusted.

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
