### PR TITLE
Fix Maryland income tax difference with TAXSIM35

### LINKED ISSUE #4161: Fix Maryland income tax difference with TAXSIM35
Difference: https://github.com/PolicyEngine/policyengine-us/discussions/4115

### PR DESCRIPTION
**Pull request by Shinuing**
fix #4161

### CODE REVIEW

**Review by PavelMakarchuk — CHANGES_REQUESTED** [review]

**Comment by Shinuing** [comment]
1. [`md_income_tax` ](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/md/tax/income/md_income_tax.py) adds and subtractions are not correct. The subtractions are some refundable credits + some non-refundable credit
image

**Comment by Shinuing** [comment]
4. Why the `md_non_refundable_eitc` and `md_refundable_eitc` are calculated exclusively instead of adding the exist refundable/non-refundable EITCs together?

**Comment by PavelMakarchuk** [comment]
> 1. [`md_income_tax` ](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/states/md/tax/income/md_income_tax.py) adds and subtractions are not correct. The subtractions are some refundable credits + some non-refundable credit
>    image

I think the additions and subtractions only refer to the adjusted gross income up until line 16:
[Form](https://www.marylandtaxes.gov/forms/21_forms/502.pdf)
image

The credits are the subtracted from the pre-credit income tax

**Comment by Shinuing** [comment]
Hi @PavelMakarchuk I have some confusions (please see above), and what I did is just try to "match" the results from TAXSIM but I figured that doing this would cause the overall structure more and more complicated and uneasy to understand. 
I spent a lot of time but confusions became more and more. I would suggest to ask the author of the old structure to modify (if he/she is still here) OR please allow me to give up what we have so far and redo the EITC of Maryland.

**Comment by PavelMakarchuk** [comment]
> 4. Why the `md_non_refundable_eitc` and `md_refundable_eitc` are calculated exclusively instead of adding the exist refundable/non-refundable EITCs together?

this should be fixed as I am not sure why this was implemented in the first place

**Comment by PavelMakarchuk** [comment]
> Hi @PavelMakarchuk I have some confusions (please see above), and what I did is just try to "match" the results from TAXSIM but I figured that doing this would cause the overall structure more and more complicated and uneasy to understand. I spent a lot of time but confusions became more and more. I would suggest to ask the author of the old structure to modify (if he/she is still here) OR please allow me to give up what we have so far and redo the EITC of Maryland.

Hey @Shinuing if there are this many issues with the current code I think the best way is to re-write it to fit our current structure. I believe this would be the easiest way to address the issue. 
Thank you for looking into this!

**Comment by PavelMakarchuk** [comment]
> > Hi @PavelMakarchuk I have some confusions (please see above), and what I did is just try to "match" the results from TAXSIM but I figured that doing this would cause the overall structure more and more complicated and uneasy to understand. I spent a lot of time but confusions became more and more. I would suggest to ask the author of the old structure to modify (if he/she is still here) OR please allow me to give up what we have so far and redo the EITC of Maryland.
> 
> Hey @Shinuing if there are this many issues with the current code I think the best way is to re-write it to fit our current structure. I believe this would be the easiest way to address the issue. Thank you for looking into this!

we should fix the EITC in one PR (as there is so much) and then move on to other credits as needed but making those incremental changes should be best

**Comment by MaxGhenis** [comment]
Adding @fedderw who originally wrote the Maryland EITC, but as he can attest it's very complex. I don't recall the intricacies but remember working through it a fair bit.

@ngpsu22 do you know any Maryland EITC experts who could advise us?

**Comment by PavelMakarchuk** [comment]
Duplicate of #4255

We got it

**Pull request closed without merging**
