### PR TITLE
Add linecheck to .github/workflows/pr.yaml file

### LINKED ISSUE #2064: Add linecheck to PR GH action

### PR DESCRIPTION
**Pull request by martinholmer**
Fixes #2064.

### Summary
🧹🐍🚦

Add linecheck formatting check to PR workflow. This helps ensure consistent and error-free Python code in the `.github/workflows/pr.yaml` file and the rest of the repository.

> _`linecheck` formats_
> _code for policy design_
> _autumn cleaning time_

### Walkthrough
*  Add a formatting check step to the workflow ([link](https://github.com/PolicyEngine/policyengine-us/pull/2796/files?diff=unified&w=0#diff-1eb4e5fd5611777d4e597ef299a1cb5ba8050c28a2dabbd4fbc56205d69e5ddaL10-R18))

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thanks Martin, have you checked that it works, eg with a test commit that removes a newline that we should have?

**Comment by martinholmer** [comment]
@MaxGhenis asked:
> have you checked that it works, eg with a test commit that removes a newline that we should have?

Don't the changes in PR #2796 need to be merged before they can be tested?

**Comment by martinholmer** [comment]
@MaxGhenis,  I got an email saying this PR had failed for the following reason:
```
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```
But I have not been able to find the GitHub linecheck repository@ref on GitHub.
Do you know who the owner is?

**Comment by martinholmer** [comment]
So I've found that PolicyEngine is the owner of the 'linecheck' repository.
But now I have another error (see below).   I wonder why you labelled this issue as a 
"good first issue".   Seem to me this is an issue that should be the responsibility of the PolicyEngine CTO.   Why wasn't this assigned to him?


Screenshot 2023-08-08 at 5 36 53 PM


Why does `linecheck` need an `action.yaml` file when `black` did not?
If it is because the `black` reference is to a Docker file, then where is the `linecheck` Docker file?

**Comment by MaxGhenis** [comment]
I listed it as a good first issue primarily because it doesn't require background knowledge on the policyengine-us project, and secondarily because I thought it would be simpler than it seems to have been. I filed https://github.com/PolicyEngine/linecheck/issues/4 to add linecheck to the GitHub Marketplace, which should help move this forward. Thanks for starting it.

**Comment by martinholmer** [comment]
On August 8 in PR #2796, @MaxGhenis asked @nikhilwoodruff:
> @nikhilwoodruff could you help?

He did this because @nikhilwoodruff is the author of the `linecheck` utility and short of developing a Docker file for `linecheck` it was not clear how `linecheck` could be used in GitHub CI.

After more than a month there has been no response from @nikhilwoodruff, so I have no idea how to proceed on resolving issue #2064.  As a result, I'm closing this pull request and leaving the resolution of issue #2064 to someone with more GitHub CI skills.

**Pull request closed without merging**
