### PR TITLE
Fix CTC full refundability and refactor ARP CTC logic

### LINKED ISSUE #1488: CTC isn't fully refundable in 2021
Pull request #1485, which generated version 0.177.0, causes unintended changes in 2021 US tax liability for tax units with low or zero income tax liability before credits.  Essentially the code refactoring in #1485 has rendered the 2021 CTC as **not** fully refundable, so many low income tax units have higher taxes in version 0.177.0 than they had in version 0.176.0.  Also, the 0.176.0 version was in agreement with TAXSIM35 for 2021 low income tax units, but now that agreement has been lost.

Here is a simple 2021 test case that shows the new differences with TAXSIM35:
```
# PolicyEngine US test file derived from p21.its.csv and p21.ots.csv files
- name: Tax unit with taxsimid 56 from p21.its.csv
  absolute_error_margin: 0.01
  period: 2021
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 68
        employment_income: 4000
        ssi: 0
        state_supplement: 0
        wic: 0
      person2:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
      person3:
        is_tax_unit_head: 0
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 1
        age: 11
        ssi: 0
        state_supplement: 0
        wic: 0
    spm_units:
      spm_unit:
        members: [person1, person2, person3]
        snap: 0
        tanf: 0
    tax_units:
      tax_unit:
        members: [person1, person2, person3]
        premium_tax_credit: 0
    households:
      household:
        members: [person1, person2, person3]
        state_code: TX
  output:
    taxsim_tfica: 306.00
    income_tax: -11800.00
```

And here are the summary results for that test case:
```
(policyengine-us) US% ../extract_case.sh p21 56
================================= FAILURES ===================================
_______________________________ test session _________________________________
/Users/mrh/work/Policy-Engine-US/US/p21-id56.test.yaml:
  Test 'Tax unit with taxsimid 56 from p21.its.csv':
    income_tax@2021: [-8600.] differs from -11800.0
                     with an absolute margin [3200.] > 0.01
========================= short test summary info ============================
FAILED p21-id56.test.yaml::
============================ 1 failed in 0.90s ===============================
Trace output is in file: p21-id56.test.trace
```

And finally, here is part of the trace output generated by the test:
```
(policyengine-us) US% ./trace.sh p21-id56       
income_tax_before_credits<2021, (default)> = [0.]
non_refundable_ctc<2021, (no_salt)> = [3200.]                    <<<<<< SHOULD BE 0
income_tax_non_refundable_credits<2021, (no_salt)> = [3950.]
income_tax_capped_non_refundable_credits<2021, (no_salt)> = [0.]
income_tax_before_refundable_credits<2021, (default)> = [0.]
refundable_ctc<2021, (no_salt)> = [2800.]                        <<<<<< SHOULD BE 6000
eitc<2021, (default)> = [1600.]
rrc_arpa<2021, (no_salt)> = [4200.]
income_tax<2021, (default)> = [-8600.]
```

### LINKED ISSUE #1549: Test failure in 0.184.2 version
@nikhilwoodruff, when I update to the 0.184.2 version and run `make test` I get this:
```
policyengine-us% grep version setup.py 
    version="0.184.2",

policyengine-us% make test            
coverage run -a --branch -m policyengine_core.scripts.policyengine_command test policyengine_us/tests/policy/ -c policyengine_us
ERROR:policyengine_core.taxbenefitsystems.tax_benefit_system:Unable to load OpenFisca variables from file "/Users/mrh/work/policyengine-us/policyengine_us/variables/input/geography.py"
Traceback (most recent call last):
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/scripts/policyengine_command.py", line 133, in <module>
    sys.exit(main())
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/scripts/policyengine_command.py", line 124, in main
    return sys.exit(main(parser))
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/scripts/run_test.py", line 18, in main
    tax_benefit_system = build_tax_benefit_system(
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/scripts/__init__.py", line 41, in build_tax_benefit_system
    country_package = importlib.import_module(country_package_name)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/mrh/work/policyengine-us/policyengine_us/__init__.py", line 10, in <module>
    from policyengine_us.system import (
  File "/Users/mrh/work/policyengine-us/policyengine_us/system.py", line 41, in <module>
    system = CountryTaxBenefitSystem()
  File "/Users/mrh/work/policyengine-us/policyengine_us/system.py", line 31, in __init__
    super().__init__(entities)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 118, in __init__
    self.add_variables_from_directory(self.variables_dir)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 337, in add_variables_from_directory
    self.add_variables_from_directory(subdirectory)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 334, in add_variables_from_directory
    self.add_variables_from_file(py_file)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 277, in add_variables_from_file
    self.add_variable(pot_variable)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 179, in add_variable
    return self.load_variable(variable, update=False)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/taxbenefitsystems/tax_benefit_system.py", line 164, in load_variable
    variable = variable_class(baseline_variable=baseline_variable)
  File "/Users/mrh/opt/anaconda3/lib/python3.9/site-packages/policyengine_core/variables/variable.py", line 248, in __init__
    raise ValueError(
ValueError: Unexpected attributes in definition of variable "medicaid_rating_area": 'hidden_input'
make: *** [test] Error 1
```

What's the problem?

### PR DESCRIPTION
**Pull request by MaxGhenis**
Fixes #1488 

Fixes #1549

### CODE REVIEW

**Comment by MaxGhenis** [comment]
@nikhilwoodruff I think this is pretty much done on the core federal CTC side, but am I right that we'll need essentially a full copy of the federal CTC Python code for the NY version of the federal CTC pinned at 2017?

**Comment by MaxGhenis** [comment]
@nikhilwoodruff thanks for offering to reimplement the pre-TCJA CTC (as used by the NY CTC) in this PR using `BranchedSimulation` to avoid code duplication.

**Comment by MaxGhenis** [comment]
@nikhilwoodruff thanks for the NY CTC fix. But I'm now getting different results between `make test` and `policyengine-core test` for the same tests. Could this suggest a leak, as in #1379?

All the CTC unit tests pass when run on their own:
```shell
(base) maxghenis@MacBook-Air-2 policyengine-us % policyengine-core test policyengine_us/tests/policy/baseline/gov/irs/credits/ctc -c policyengine_us         
====================================================================== test session starts =======================================================================
platform darwin -- Python 3.7.11, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /Users/maxghenis/PolicyEngine/policyengine-us
plugins: anyio-3.5.0, dependency-0.5.1
collected 31 items                                                                                                                                               

policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/ctc.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/integration.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/non_refundable_ctc.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/ctc_qualifying_child.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_adult_individual_maximum.yaml .....
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_child_individual_maximum.yaml .....
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_child_individual_maximum_arpa.yaml ..
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/ctc_phase_out.yaml ..
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/ctc_phase_out_threshold.yaml ..
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/arpa/ctc_arpa_addition.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/arpa/ctc_arpa_max_addition.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/arpa/ctc_arpa_phase_out_cap.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/arpa/ctc_arpa_uncapped_phase_out.yaml ...
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/refundable/ctc_limiting_tax_liability.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/refundable/ctc_refundable_maximum.yaml ....

======================================================================= 31 passed in 0.69s =======================================================================
```
But they fail with `make test`:
```shell
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_adult_individual_maximum.yaml ...F.
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_child_individual_maximum.yaml ..F.F
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_child_individual_maximum_arpa.yaml ..
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/ctc_phase_out.yaml ..
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/ctc_phase_out_threshold.yaml FF
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/arpa/ctc_arpa_addition.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/arpa/ctc_arpa_max_addition.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/arpa/ctc_arpa_phase_out_cap.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/arpa/ctc_arpa_uncapped_phase_out.yaml ...
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/refundable/ctc_limiting_tax_liability.yaml .
policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/refundable/ctc_refundable_maximum.yaml .F.F
policyengine_us/tests/policy/baseline/gov/irs/credits/earned_income/earned_income_tax_credit.yaml ^C^C

============================================================================ FAILURES ============================================================================
__________________________________________________________________________ test session __________________________________________________________________________
/Users/maxghenis/PolicyEngine/policyengine-us/policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_adult_individual_maximum.yaml:
  Test 'Adult dependents got $500 in TCJA.':
    ctc_adult_individual_maximum@2018: [0.] differs from 500.0 with an absolute margin [500.] > 0
__________________________________________________________________________ test session __________________________________________________________________________
/Users/maxghenis/PolicyEngine/policyengine-us/policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_child_individual_maximum.yaml:
  Test 'CTC rose to $2,000 post-TCJA.':
    ctc_child_individual_maximum@2018: [1000.] differs from 2000.0 with an absolute margin [1000.] > 0
__________________________________________________________________________ test session __________________________________________________________________________
/Users/maxghenis/PolicyEngine/policyengine-us/policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/maximum/individual/ctc_child_individual_maximum.yaml:
  Test 'Post-ARP CTC provided $2,000 to young and non-young children.':
    ctc_child_individual_maximum@2022: [1000.] differs from 2000.0 with an absolute margin [1000.] > 0
__________________________________________________________________________ test session __________________________________________________________________________
/Users/maxghenis/PolicyEngine/policyengine-us/policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/ctc_phase_out_threshold.yaml:
  Test 'CTC phases out at $200,000 for singles while TCJA is active.':
    ctc_phase_out_threshold@2020: [75000.] differs from 200000.0 with an absolute margin [125000.] > 0
__________________________________________________________________________ test session __________________________________________________________________________
/Users/maxghenis/PolicyEngine/policyengine-us/policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/phase_out/ctc_phase_out_threshold.yaml:
  Test 'CTC phases out at $400,000 for singles while TCJA is active.':
    ctc_phase_out_threshold@2022: [110000.] differs from 400000.0 with an absolute margin [290000.] > 0
__________________________________________________________________________ test session __________________________________________________________________________
/Users/maxghenis/PolicyEngine/policyengine-us/policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/refundable/ctc_refundable_maximum.yaml:
  Test '$1,500 was refundable in 2020.':
    ctc_refundable_maximum@2020: [1000.] differs from 1400.0 with an absolute margin [400.] > 0
__________________________________________________________________________ test session __________________________________________________________________________
/Users/maxghenis/PolicyEngine/policyengine-us/policyengine_us/tests/policy/baseline/gov/irs/credits/ctc/refundable/ctc_refundable_maximum.yaml:
  Test '$1,500 was refundable in 2022.':
    ctc_refundable_maximum@2022: [1000.] differs from 1500.0 with an absolute margin [500.] > 0
```

**Comment by MaxGhenis** [comment]
Some of these test failures don't involve the CTC, e.g. the `income_tax_before_credits` in `gov/irs/tax/federal_income/validation.yaml` is changing from $35,473 to $37,457. I ran this test on master and verified it's correct against taxsim.

@nikhilwoodruff before I compare the computation trees, is there a chance the policyengine-core changes could be affecting itemization in some way? I'd prefer adding unit tests over comparing computation trees if you could suggest any themes.

**Comment by nikhilwoodruff** [comment]
Awesome, thanks Max!

**Pull request merged**
