### PR TITLE
Separate `takes_up_snap_if_eligible` variable

### LINKED ISSUE #5113: Separate `takes_up_snap_if_eligible` variable
Currently take-up logic is in `snap`. Separating it would improve modularity and more easily enable us to estimate the effect of different take-up rates.

### PR DESCRIPTION
**Pull request by vrathi101**
Fixes #5113

### CODE REVIEW

**Comment by MaxGhenis** [comment]
@nikhilwoodruff what's the best way to do this? should we check we're in a microsim within the take-up variable?

**Review by nikhilwoodruff — APPROVED** [review]
This looks fine @MaxGhenis - still preserves that behaviour.

But please don't merge yet as currently tests will fail if re-run.

**Comment by nikhilwoodruff** [comment]
I'm pulling in this PR to @PavelMakarchuk's SALT PR #5053

**Comment by MaxGhenis** [comment]
Thanks! We put this into #5053

**Pull request closed without merging**
