### PR TITLE
Add post-TCJA income tax rates

### LINKED ISSUE #5126: Add post-TCJA income tax rates
We currently just account for the main tax rate change

### PR DESCRIPTION
**Pull request by PavelMakarchuk**
Fixes #5126

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Cand you cite IRC

**Comment by PavelMakarchuk** [comment]
> Cand you cite IRC

I can not find an IRC reference, 
Third party shops all describe these rates
[Example](https://www.cato.org/blog/2026-tax-increases-one-chart)
[Efile](https://www.efile.com/2026-tax-year-changes-tcja/)
[CBO](https://www.cbo.gov/budget-options/58634)

The [legal code](https://www.law.cornell.edu/uscode/text/26/1) does not state post TCJA tax rates

**Comment by MaxGhenis** [comment]
IRC(1) provides the pre/post-TCJA rates in (a-d). TCJA is in (j).

**Comment by PavelMakarchuk** [comment]
> IRC(1) provides the pre/post-TCJA rates in (a-d). TCJA is in (j).

(a-d) does not align with projections of other shops as far I can see
Law
image

CBO:
image

**Comment by MaxGhenis** [comment]
See [IRC(1)(i)](https://www.law.cornell.edu/uscode/text/26/1#i), which specifies rate reductions after 2000

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
