### PR TITLE
Fix New York supplemental tax calculations

### LINKED ISSUE #3546: Fix New York supplemental tax calculations
Using the 0.601.0 version, there are many tax differences in the amounts for the `ny_income_tax_before_credits` variable in comparison with TAXSIM35 even though the two models produce the same NY AGI and same NY taxable income amounts.  

In fact, pull request #3373, which was intended to fix issue #1679, actually **increased** the number of `e21` sample tax differences rather than reducing them.

The problem, as originally pointed out in issue #1679, is that PolicyEngine-US logic does not, in all cases, follow the logic of the simple supplemental income tax worksheets included in the NY income tax instructions.

The way to eliminate these differences is to create a 2021 test for each of the several supplemental tax worksheets (where the output is calculated by hand given AGI and taxable income), and then prepare a pull request that modifies the code so that all those tests pass.

### PR DESCRIPTION
**Pull request by Shinuing**
Fixes #3546

### CODE REVIEW

**Comment by Shinuing** [comment]
Hello @martinholmer 

Let me know if this is what you want. Now the test includes **ALL** 16 tax computation worksheets in the [Form IT 201](https://www.tax.ny.gov/pdf/2021/inc/it201i_2021.pdf#page=52)

In fact, the number of `e21` sample tax differences is not reduced

**Comment by martinholmer** [comment]
@Shinuing, I'm not sure why this is true but I cannot get the same answer as you do for one of the tests you are adding in pull request #3568.  Here is the test:

```
- name: Unit test 1 for 2021 New York supplemental tax married filing jointly and qualifying widow(er)
  absolute_error_margin: 0.1
  period: 2021
  input:
    state_code: NY
    filing_status: JOINT
    ny_agi: 110_000 # $107,650 < AGI < $25,000,000
    ny_taxable_income: 27_900 # <$161,550
    ny_main_income_tax: 1_202
  output:
    ny_supplemental_tax: 1609.136 # 27900*5.97%-(110000-107650)/50000*1202
    # 2021 NY Form IT-201 Instructions Tax computation worksheet 1 
```

I don't understand why you think the `ny_supplemental_tax` for this case should be $1609.136.   When I fill out the tax calculation worksheet I get a different amount for the supplemental tax.   Did I make mistakes in the hand calculation below?

```
# 2021 NY Tax Computation Worksheet 1:
# Line1: 110_000.00   = ny_agi (INPUT)
# Line2:  27_900.00   = ny_taxable_income (INPUT)
# Line3:   1_665.63   = Line2 * 5.97%
# Line4:   1_202.00   = ny_main_income_tax (INPUT)
# Line5:     463.63   = Line3 - Line4 = 1_665.63 - 1_202.00
# Line6:   2_350.00   = Line1 - 107_650 = 110_000 - 107_650
# Line7:     0.0470   = Line6 / 50_000 = 2_350 / 50_000
# Line8:      21.79   = Line5 * Line7 = 463.63 * 0.047 = ny_supplemental_tax
# Line9:   1_223.79   = Line4 + Line8 = 1202.00 + 21.79 = ny itax pre credits
```
So, instead of your $1,609.14, I get $21.79.  That's a big difference.
Why are we getting such different results?

**Comment by Shinuing** [comment]
@martinholmer The calculation is correct. As I mentioned in #3546  , there is an exception when the taxable income is less than $43,000

### 1. $43,000 < taxable income < $161,550
```
# Input
    ny_agi: 110_000 # $107,650 < AGI < $25,000,000
    ny_taxable_income: 100_000 # $43,000<$161,550
    ny_main_income_tax: 5_495.8
```
**2021 NY Tax Computation Worksheet 1:**
Line1:  110_000.00   = ny_agi (INPUT)
Line2:  100_000   = ny_taxable_income (INPUT)
Line3:  5_970   = Line2 * 5.97%
Line4:  5_495.8   = ny_main_income_tax (INPUT)
Line5:  474.2  = Line3 - Line4 = 5_970-5_495.8
Line6:  2_350.00   = Line1 - 107_650 = 110_000 - 107_650
Line7:  0.0470   = Line6 / 50_000 = 2_350 / 50_000
Line8:  22.2874  = Line5 * Line7 = 474.2 * 0.047 = ny_supplemental_tax
Line9:  5_518.09   = Line4 + Line8 = 5_495.8 + 22.2874 = ny itax pre credits

**NY Law Section 601 (my structure)**
recapture base = 0
incremental benefit = 474
applicable amount = agi - 107,650 = 2,350
phase-in fraction = min(applicable amount, 50000)/50000 = 2350/50000 = 0.047
supplemental tax = recapture base + incremental benefit * phase-in fraction = 0 + 474 * 0.047 = 22.278

_22.2874 ≈ 22.278, I would assume those two results match_

### 2. taxable income < $43,000
```
# Input
    ny_agi: 110_000 # $107,650 < AGI < $25,000,000
    ny_taxable_income: 27_900 # <$161,550
    ny_main_income_tax: 1_202
```

**2021 NY Tax Computation Worksheet 1 result**  = 21.79

**NY Section 601**
supplemental tax 
= taxable income * 5.97% - ny main tax * [min(50_000, agi-107_650)/50_000] 
= 27_900 * 5.97%-(110_000-107_650)/50_000*1_202
= 1_609.136
Screen Shot 2024-01-24 at 9 56 07 PM

By law, the calculation is different when the taxable income is <$43,000. Even so, it is still in the range of less than $161,550. I don't know why this calculation is not in the computation table. But I thought it would be best to include all cases. Please let me know if I am missing something.

**Comment by Shinuing** [comment]
@PavelMakarchuk 

Removed the calculation of low taxable income and the results should now be align with Martin

To achieve this, both the lower threshold for recapture base and incremental benefits should be set to 0, otherwise `ny_supplemental_tax` will be 0.

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk
> 
> Removed the calculation of low taxable income and the results should now be align with Martin
> 
> To achieve this, both the lower threshold for recapture base and incremental benefits should be set to 0, otherwise `ny_supplemental_tax` will be 0.

Can we delete the parameter files all together? Or do we need those somewhere else?

**Comment by PavelMakarchuk** [comment]
> > Can we delete the parameter files all together? Or do we need those somewhere else?
> 
> No, we need parameters. The only modification is the bottom threshold

Ok perfect, then it looks good to me

**Pull request merged**
