### PR TITLE
Fix the repeal dependent exemption reform

### LINKED ISSUE #5000: Repealing the dependent exemption does not have any impacts
[Example](https://policyengine.org/us/policy?reform=65060&focus=policyOutput.policyBreakdown&region=enhanced_us&timePeriod=2026&baseline=2)

### PR DESCRIPTION
**Pull request by PavelMakarchuk**
Fixes #5000

### CODE REVIEW

**Review by MaxGhenis — COMMENTED** [review]
why didn't the earlier approach work?

**Comment by PavelMakarchuk** [comment]
> why didn't the earlier approach work?

I am not entirely sure, it seems to be the way we compute `tax_unit_size`  but it seems to be fixed by swapping that variable out in `exemptions` for `head_spouse_count`

**Comment by MaxGhenis** [comment]
Can you look more into the previous approach? It'd be much cleaner. Add a unit test to debug?

**Comment by PavelMakarchuk** [comment]
> Can you look more into the previous approach? It'd be much cleaner. Add a unit test to debug?

Five year forward check was not applied, we get impacts if repealing starting 2024 and checking other years 
[Example](https://policyengine.org/us/policy?focus=policyOutput.policyBreakdown&reform=65061&region=enhanced_us&timePeriod=2026&baseline=2)

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
