### PR TITLE
Add and remove index files based on state progress

### LINKED ISSUE #2986: Add Louisiana and other unfinished index files and remove New Jersey and Indiana index files

### LINKED ISSUE #2988: Remove index.yaml for other states
@PavelMakarchuk correctly noted that the `index.yaml` parameter file for IN income tax should be removed because that state income tax testing in issue #993 has been completed successfully.

But this is also true of the following states that have income tax `index.yaml` files:
DC
MA (two index.yaml files deep in the parameter directory tree)
MO

### PR DESCRIPTION
**Pull request by PavelMakarchuk**
Fixes #2986

Fixes #2988

### Summary
🐛🗑️🗺️

This change renames some state index files and updates the changelog entry for the next patch release of PolicyEngine US. The change improves the state-level data and policies for Louisiana and Connecticut, and removes the outdated ones for Indiana and New Jersey.

> _`PolicyEngine` patch_
> _Fixing state index files_
> _Autumn leaves fall fast_

### Walkthrough
*  Rename state index files to reflect updated data sources and policies ([link](https://github.com/PolicyEngine/policyengine-us/pull/2987/files?diff=unified&w=0#diff-5db22fb6960e62088f85bd18a01176d8ccd779ea126ac5eeb517cf4250ece641), [link](https://github.com/PolicyEngine/policyengine-us/pull/2987/files?diff=unified&w=0#diff-5ae96448698112d7e524a6addc7701bddb19e3feaeb4573e0add6565edfc10ec))
*  Update `changelog_entry.yaml` to document the patch release and the state index file changes ([link](https://github.com/PolicyEngine/policyengine-us/pull/2987/files?diff=unified&w=0#diff-5885042762833a4aef51405a4036067e4e6aefa7a5091a2987d1d9d1fc2647e8R1-R5))

- as per #993 indiana and New Jersey pass the integration tests

### CODE REVIEW

**Comment by martinholmer** [comment]
@PavelMakarchuk,  See issue #2988 for other removals.

Other states that need an `index.yaml` file include:
CA, NY, OR, UT

Plus, I guess you should add an `index.yaml` file for all the states that are so early on in their income tax develop that they are listed in issue #993 as "untestable".

How are you planning to handle the states with no income tax like TX, FL, etc.?

**Comment by PavelMakarchuk** [comment]
> @PavelMakarchuk, See issue #2988 for other removals.
> 
> Other states that need an `index.yaml` file include: CA, NY, OR, UT
> 
> Plus, I guess you should add an `index.yaml` file for all the states that are so early on in their income tax develop that they are listed in issue #993 as "untestable".
> 
> How are you planning to handle the states with no income tax like TX, FL, etc.?

@MaxGhenis would we index the states that have been previously completed but have not passed the integration testing? Just making sure that we have not announced launches before rolling it back in the app

**Comment by MaxGhenis** [comment]
Which states would those be? Only Oregon comes to mind right now, which yes we can roll back.

**Comment by PavelMakarchuk** [comment]
> CA, NY, OR, UT

Martin mentioned: CA, NY, OR, UT

**Comment by MaxGhenis** [comment]
CA NY and UT aren't passing taxsim validation? Martin could you share how far off we are?

**Comment by MaxGhenis** [comment]
Never mind - I see open issues linked in https://github.com/PolicyEngine/policyengine-us/issues/993

**Comment by martinholmer** [comment]
@MaxGhenis said in PR #2987:
> Never mind - I see open issues linked in https://github.com/PolicyEngine/policyengine-us/issues/993

Yes, so in #993 you can see that:

CA is not passing all the tests in the ***third** `g21` sample.
NY is not passing all the tests in the **first** `e21` sample.
UT is not passing all the tests in the **first** `p21` sample.

So, there three states have not gotten very far in the integration testing process.
The `e21` through `k21` sequence of samples, for example, has 800,000 tests.

**Comment by PavelMakarchuk** [comment]
I believe it would be best to merge this PR with LA added and Missouri removed index files as those are complete/incomplete beyond doubt. - for the other states we can talk about whether we want to pull them off of the site as we are working on the created issues f.e. UT

**Review by MaxGhenis — CHANGES_REQUESTED** [review]
Could we leave the existing files in rent/ property tax folders there? Once we complete the state tax models otherwise we'll still want those until we impute rent and property tax to the CPS

**Comment by PavelMakarchuk** [comment]
> Could we leave the existing files in rent/ property tax folders there? Once we complete the state tax models otherwise we'll still want those until we impute rent and property tax to the CPS

Does this relate to the index files?

**Comment by MaxGhenis** [comment]
yes

**Review by MaxGhenis — APPROVED** [review]
I just checked out the PR and verified that the existing renter/property tax credit index.yaml files remain, despite GitHub (incorrectly) claiming that the new ones are moved files rather than created ones. Merging.

**Pull request merged**
