### PR TITLE
Add test to prevent inadvertently making 2021 CDCC non-refundable

### PR DESCRIPTION
**Pull request by martinholmer**
The added test is from issue #1571.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
Thanks, could you just rename the file to integration.yaml? We reserve naming the tests with the name of the variable for unit tests.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Thanks, could you just rename the file to integration.yaml? We reserve naming the tests with the name of the variable for unit tests.

There is already a unit test in the `cdcc.yaml` file, so I changed the new test to be a unit test (rather than rename the file).   Should be ready to merge.

**Comment by MaxGhenis** [comment]
We'd still consider this an integration test. Since the [`cdcc` formula](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/irs/credits/cdcc/cdcc.py) only has two inputs--`cdcc_relevant_expenses` and `cdcc_rate`--a unit test would only have those inputs as well.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> We'd still consider this an integration test. Since the [cdcc formula](https://github.com/PolicyEngine/policyengine-us/blob/master/policyengine_us/variables/gov/irs/credits/cdcc/cdcc.py) only has two inputs--cdcc_relevant_expenses and cdcc_rate -- a unit test would only have those inputs as well.

Max, it's good to have standards, but it seems to me you are setting a double standard in this case.   When I look at the old test in the `cdcc.yaml` file, I see that it is not a unit test by the above definition.  Yet this old test was developed by @nikhilwoodruff and reviewed and approved by you as part of PR #821.  So, why was that test in the `cdcc.yaml` file?

**Comment by MaxGhenis** [comment]
I'd missed that the current test is an integration test, you're right. We might have refactored the CDCC code and not mirrored that to the test, or we may have been still developing our policy in May. Could you rename the full file to integration.yaml?

I also filed https://github.com/PolicyEngine/policyengine-us/issues/1646 to catch up our code to this standard.

**Review by MaxGhenis — APPROVED** [review]

**Pull request merged**
