### PR TITLE
Move ignored credit list to a parameter file

### PR DESCRIPTION
**Pull request by martinholmer**
Should have been included in pull request #1526.

### CODE REVIEW

**Comment by MaxGhenis** [comment]
I think this might actually be all refundable credits, in which case we can use `parameters(period).gov.irs.credits.refundable`.

The instructions are contradictory though so curious what you think:

## Legal code

[Section 143.171](https://revisor.mo.gov/main/OneSection.aspx?section=143.171)(2)(1) says (emphasis mine):
> Notwithstanding any other provision of law to the contrary, for all tax years beginning on or after January 1, 2019, an individual taxpayer shall be allowed a deduction equal to a percentage of his or her federal income tax liability under Chapter 1 of the Internal Revenue Code for the same taxable year for which the Missouri return is being filed, not to exceed five thousand dollars on a single taxpayer's return or ten thousand dollars on a combined return, **after reduction for all credits thereon**, except the credit for payments of federal estimated tax, the credit for the overpayment of any federal tax, and the credits allowed by the Internal Revenue Code by 26 U.S.C. Section 31, 26 U.S.C. Section 27, and 26 U.S.C. Section 34.

We don't model those exempted credits (i.e. those that would still be counted as tax):
* [IRC Section 31](https://www.law.cornell.edu/uscode/text/26/31) is tax withheld on wages
* [IRC Section 27](https://www.law.cornell.edu/uscode/text/26/27) is tax of foreign country and United States possessions
* [IRC Section 34](https://www.law.cornell.edu/uscode/text/26/34) is tax on certain uses of gasoline, special fuels and lubricating oils

Subsection 2 covers the recovery rebates, but seems essentially redundant with subsection 1.

## Tax form

The [2021 MO-1040](https://dor.mo.gov/forms/MO-1040%20Fillable%20Calculating_2021.pdf) only asks for `Tax from federal return` (line 9) and `Other tax from federal return` (line 10); the sum is the base for the deduction.

The [2021 MO-1040 instruction booklet](https://dor.mo.gov/forms/MO-1040%20Instructions_2021.pdf#page=7) says for line 9 (emphasis mine):
>**Use the chart in next column to locate your tax on your federal return.** Do not enter your federal income tax withheld as shown on your Form(s) W-2 or federal return. **If you have an earned income credit, you must subtract the credit from the tax on your federal return.** If a negative amount is calculated, enter “0”. If you used a method other than the federal tax table to determine your federal tax, attach the appropriate schedule.

image

Here's where I think a contradiction may lie: the [2021 federal 1040](https://www.irs.gov/pub/irs-pdf/f1040.pdf) shows it would not ignore the ACTC (line 28):
image

But line 15 from the [2021 federal 1040X](https://www.irs.gov/pub/irs-pdf/f1040x.pdf) includes Schedule 8812, the ACTC. 
image

We could clarify this from the DOR and/or see what taxsim does, but all else equal seems like subtracting all refundable credits would be the simplest starting point most aligned to the law.

**Comment by martinholmer** [comment]
@MaxGhenis, You seem to be suggesting the list of ignored credits is the same as the list of **all** refundable federal credits, which is this:
```
description: Refundable tax credits.
values:
  2013-01-01:
    - eitc
    - refundable_american_opportunity_credit
    - refundable_ctc
    - recovery_rebate_credit
    - refundable_payroll_tax_credit
    - premium_tax_credit
  # Add CDCC in 2021.
  2021-01-01:
    - eitc  # <<<<<<<<<<<<<<<<<<<<<<<<
    - refundable_american_opportunity_credit  # not in TAXSIM35
    - refundable_ctc  # can't calculate because of issue #1488
    - recovery_rebate_credit  # <<<<<<<<<<<<<<<<<<<<<<<<
    - refundable_payroll_tax_credit  # what is this? has no formula!
    - premium_tax_credit  # not in TAXSIM35
    - cdcc  # can't calculate because of issue #1488
  # Remove CDCC in 2022.
  2022-01-01:
    - eitc
    - refundable_american_opportunity_credit
    - refundable_ctc
    - recovery_rebate_credit
    - refundable_payroll_tax_credit
    - premium_tax_credit
```

Where exactly on the form or in the legislative language does it say to ignore the AOC and the CTC and the ACA PTC and the CDCC?

I can't test whether or not the CTC or CDCC in 2021 are ignored because, at the moment, PolicyEngineUS does not compute correct 2021 CTC amounts (per issue #1488).

This pull request makes no substantive changes from #1526, which you merged without asking any questions.  So, I'm confused about why all the questions now.

Why not merge this non-substantive, stylistic pull request now.  Then we will find out in the course of further validation testing (after issue #1488 is fixed) whether or not TAXSIM35 considers the 2021 CTC and CDCC to be ignored credits for the MO federal income tax deduction.

**Comment by martinholmer** [comment]
The federal form line numbers in the box you reproduce are unreliable because the MO-1040 form instruction says this about the line numbers in that box:

Screen Shot 2022-11-27 at 9 19 17 PM

There is ample evidence that both the MO legislative language and the MO-1040 form instructions are vague and even sometimes contradictory.

**Comment by MaxGhenis** [comment]
Sure I'll merge this and we can continue the investigation in https://github.com/PolicyEngine/policyengine-us/discussions/1528. Thanks Martin.

**Pull request merged**
