### PR TITLE
Use a reform instead of a parameter to simulate taxsim's incorrectnesses

### LINKED ISSUE #1090: Create reform to resemble taxsim
e.g. phasing out EITC with respect to investment income instead of a cliff

For validation

### PR DESCRIPTION
**Pull request by MaxGhenis**
Fixes #1090

### CODE REVIEW

**Comment by MaxGhenis** [comment]
@nikhilwoodruff I tried `reform: policyengine_us.reforms.taxsim.taxsim` and `reforms: policyengine_us.reforms.taxsim.taxsim` per your suggestion. In both cases though I get the following error when running the test:
>Could not parse situation described: {'reforms': 'Some entities in the situation are not defined in the loaded tax and benefit system.These entities are not found: reforms.The defined entities are: marital_units, families, people, tax_units, households, spm_units.'}

Could you advise?

**Comment by MaxGhenis** [comment]
Thanks that worked! Now going to remove the taxsim parameter to make it a structural reform.

**Comment by martinholmer** [comment]
@MaxGhenis,  We haven't discussed this and what you are doing in PR #1520 will make my TAXSIM35 validation much more difficult or perhaps impossible.   I'm not sure you are considering all the ramification of this PR.

**Comment by MaxGhenis** [comment]
@martinholmer why would it make your validation harder? The yaml test changes would be a one-liner as shown in this PR.

**Comment by martinholmer** [comment]
@MaxGhenis said:
> Now going to remove the taxsim parameter to make it a structural reform.

By this, I thought you meant you were going to remove the parameter called
`contrib/nber/taxsim35_emulation`.  But looking at your code revision (so far), it appears as if you are keeping it.   Is that correct?

**Comment by MaxGhenis** [comment]
I will remove the parameter and replace it with a structural reform, but the yaml test files will be identical.

**Comment by MaxGhenis** [comment]
Done in #1672

**Pull request closed without merging**
